---
title: "MODULES 07 AND 08"
author: "Emily Messer"
date: "2/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Challenge 1

```{r }
d <- ("There is grandeur in this view of life, with its several powers, having been originally breathed by the Creator into a few forms or into one; and that, whilst this planet has gone circling on according to the fixed law of gravity, from so simple a beginning endless forms most beautiful and most wonderful have been, and are being evolved")
d
?str_split()
library(stringr)
s<- str_split(d, ' ')[[1]]
everyfourth <- s[seq(from=1, to=length(s), 4)]
everyfourth
sort(everyfourth, decreasing = TRUE)
```

## Challenge 2

```{r }
m <- 1:159
m <- m[seq(from = 1, to = 159, by = 2)]
m

m1 <- matrix(
  data = c(m),
  nrow = 8,
  ncol = 10
  )
m1

(m1[5,2])
(m1[5:7,])

m2 <- (m1[3:6, 4:9])
m2
class(m2)
mode(m2)
```

## Challenge 3

```{r }
a <-array(data = 400:1, dim = c(5, 5, 4, 4))
a
(a[1, 1, 1, 2]) 
(a[2, 3, 2, ])
(a[1:5, 1:5, 3, 3])
```

## Challenge 4

```{r }
superfamily = list(Lorisoidea = "Lorisidae", "Galagidae", Lemuroidea = "Cheirogaleidae", "Lepilemuridae", "Indriidae", "Lemuridae", "Daubentoniidae", Tarsioidea = "Tarsiidae", Ceboidea = "Cebidae", "Atelidae", "Pitheciidae", Hominoidea = "Hylobatidae", "Hominidae", Cercopithecoidea = "Cercopithecidae")
parvorder = list(Platyrrhini = "Ceboidea", Catarrhini = "Hominoidea", "Cercopithecoidea")
infraorder = list(Lorisiformes = "Lorisidae", Lemuriformes = "Lemuroidea", Tarsiiformes = "Tarsiidae", Simiiformes = "Platyrrhini", "Catarrhini" )
suborder = list(Strepsirhini = "Lorisiformes", "Lemuriformes", Haplorhini = "Tarsiiformes", "Simiiformes")
primates = list(suborder, infraorder, parvorder, superfamily)

nwm <-primates[[3]] [1]  
class(nwm)  
mode(nwm)

primates[[2]]$Tarsiiformes
```

